### PR TITLE
Adding Github backend

### PR DESCRIPTION
**Pull request by EduardGomezEscandell**
Reports bugs as Github Issues to a given repository. This is done with Ubuntu WSL in mind, but can be easily adapted for other purposes.

### Authentication
Uses Github's Device flow:
https://docs.github.com/en/developers/apps/building-oauth-apps/authorizing-oauth-apps#device-flow

This means that the user is given this message:

> Input the following code in your browser:
> URL: https://github.com/login/device
> Code: B45A-7491

And this is used to authenticate.

### CODE REVIEW

**Comment by EduardGomezEscandell** [comment]
Currently I have the following issues, as seen in the console:
```
$ ubuntu-bug python3
```
First, it fails to find attach_casper_md5check
```
ERROR: hook /usr/share/apport/general-hooks/ubuntu.py crashed:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/apport/report.py", line 241, in _run_hook
    symb["add_info"](report, ui)
  File "/usr/share/apport/general-hooks/ubuntu.py", line 84, in add_info
    apport.hookutils.attach_casper_md5check(report,
AttributeError: module 'apport.hookutils' has no attribute 'attach_casper_md5check'
```

Afterwards, when clicking on the github link, it doesn't open, and it shows:
```
(apport-gtk:1416): Gdk-WARNING **: 09:23:37.764: Server is missing xdg_foreign support

(apport-gtk:1416): Gtk-WARNING **: 09:23:37.765: Unable to show 'https://github.com/login/device': Operation not supported
```
I can still acces it via Right click > Copy link address.

Finally, the link to the issue, automaticallu openened at end, is opened via `/usr/bin/lynx`. I'd like to open it from Windows' side to use Windows' default browser.

**Comment by bdrung** [comment]
Better use `requests` (it support proxies and stuff). To make the test happy, you have to add `python3-requests` to `.github/workflows/ci.yaml`.

**Comment by EduardGomezEscandell** [comment]
Force-pushed after rebasing to catch up to main branch

**Comment by EduardGomezEscandell** [comment]
## Status
It works, there as some UX improvements possible but I believe they are best left for a future PR. These include:
- Opening links on the Windows browser
- Making the login code copy-paste-able.

## Blocking aspects
File `etc/apport/crashdb.conf` uses a Github App ID linked to my account to talk to the Github API:

https://github.com/canonical/apport/blob/7a9f870e6f3f326df084b7821e241c8b8e674885/etc/apport/crashdb.conf#L27-L34

This has to be changed to an Ubuntu account before this PR is merged (I'm on it)

**Comment by EduardGomezEscandell** [comment]
Closing this PR because this work was taken over in #26.

**Pull request closed without merging**
